<?php

namespace ContainerQB9ptbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F4LxzJxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F4LxzJx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F4LxzJx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'table' => ['privates', 'App\\Service\\Table', 'getTableService', true],
            'user' => ['privates', '.errored..service_locator.F4LxzJx.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.F4LxzJx": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'table' => 'App\\Service\\Table',
            'user' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
