<?php

namespace ContainerQB9ptbi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterestRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\InterestRepository' shared autowired service.
     *
     * @return \App\Repository\InterestRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'InterestRepository.php';

        return $container->privates['App\\Repository\\InterestRepository'] = new \App\Repository\InterestRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
