<?php

namespace ContainerCrBlg5e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OmZMQmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Om_zMQm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Om_zMQm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'linkCaptureRepository' => ['privates', 'App\\Repository\\LinkCaptureRepository', 'getLinkCaptureRepositoryService', true],
        ], [
            'linkCaptureRepository' => 'App\\Repository\\LinkCaptureRepository',
        ]);
    }
}
