<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCron_ValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cron.validator' shared service.
     *
     * @return \Cron\Validator\CrontabValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['cron.validator'] = new \Cron\Validator\CrontabValidator();
    }
}
