<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronListCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.Cron\CronBundle\Command\CronListCommand' shared service.
     *
     * @return \Cron\CronBundle\Command\CronListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.Cron\\CronBundle\\Command\\CronListCommand'] = new \Cron\CronBundle\Command\CronListCommand($container);
    }
}
