<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttplug_StreamFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'httplug.stream_factory' shared service.
     *
     * @return \Http\Message\StreamFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['httplug.stream_factory'] = \Http\Discovery\StreamFactoryDiscovery::find();
    }
}
