<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Http_ClientService extends App_KernelProdContainer
{
    /*
     * Gets the public 'hwi_oauth.http.client' shared service.
     *
     * @return \Http\Client\Common\HttpMethodsClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['hwi_oauth.http.client'] = new \Http\Client\Common\HttpMethodsClient((new \Http\Client\Common\PluginClientFactory())->createClient((new \Http\HttplugBundle\ClientFactory\AutoDiscoveryFactory())->createClient([]), [0 => new \Http\Client\Common\Plugin\ContentLengthPlugin(), 1 => new \Http\Client\Common\Plugin\RedirectPlugin(['preserve_header' => true, 'use_default_for_multiple' => true])], ['client_name' => 'app']), ($container->services['hwi_oauth.http.message_factory'] ?? $container->load('getHwiOauth_Http_MessageFactoryService')));
    }
}
