<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwner_AzureService extends App_KernelProdContainer
{
    /*
     * Gets the public 'hwi_oauth.resource_owner.azure' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['hwi_oauth.resource_owner.azure'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner(new \Http\Client\Common\HttpMethodsClient(($container->services['hwi_oauth.http.client'] ?? $container->load('getHwiOauth_Http_ClientService')), ($container->services['hwi_oauth.http.message_factory'] ?? $container->load('getHwiOauth_Http_MessageFactoryService'))), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), ['client_id' => $container->getEnv('AZURE_CLIENT_ID'), 'client_secret' => $container->getEnv('AZURE_CLIENT_SECRET'), 'scope' => 'User.Read offline_access', 'options' => ['infos_url' => 'https://graph.microsoft.com/v1.0/me', 'application' => 'common', 'csrf' => true], 'paths' => []], 'azure', new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))));
    }
}
