<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttplug_Psr17UploadedFileFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'httplug.psr17_uploaded_file_factory' shared service.
     *
     * @return \Psr\Http\Message\UploadedFileFactoryInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['httplug.psr17_uploaded_file_factory'] = \Http\Discovery\Psr17FactoryDiscovery::findUploadedFileFactory();
    }
}
