<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInterestSearchTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Search\InterestSearchType' shared autowired service.
     *
     * @return \App\Form\Search\InterestSearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Search\\InterestSearchType'] = new \App\Form\Search\InterestSearchType();
    }
}
