<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpu_Oauth2_Client_AzureService extends App_KernelProdContainer
{
    /*
     * Gets the public 'knpu.oauth2.client.azure' shared service.
     *
     * @return \KnpU\OAuth2ClientBundle\Client\Provider\AzureClient
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['knpu.oauth2.client.azure'] = new \KnpU\OAuth2ClientBundle\Client\Provider\AzureClient((new \KnpU\OAuth2ClientBundle\DependencyInjection\ProviderFactory(($container->services['router'] ?? $container->getRouterService())))->createProvider('TheNetworg\\OAuth2\\Client\\Provider\\Azure', ['clientCertificatePrivateKey' => '', 'clientCertificateThumbprint' => '', 'clientId' => $container->getEnv('AZURE_CLIENT_ID'), 'clientSecret' => $container->getEnv('AZURE_CLIENT_SECRET'), 'urlLogin' => 'https://login.microsoftonline.com/', 'pathAuthorize' => '/oauth2/authorize', 'pathToken' => '/oauth2/token', 'scope' => [], 'tenant' => 'common', 'urlAPI' => 'https://graph.windows.net/', 'resource' => NULL, 'API_VERSION' => '1.6', 'authWithResource' => true, 'defaultEndPointVersion' => '1.0'], 'connect_azure_check', [], []), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
