<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\LinkType' shared autowired service.
     *
     * @return \App\Form\LinkType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\LinkType'] = new \App\Form\LinkType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
