<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LanguageRepository' shared autowired service.
     *
     * @return \App\Repository\LanguageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LanguageRepository'] = new \App\Repository\LanguageRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
