<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaSocialNetworkTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MediaSocialNetworkType' shared autowired service.
     *
     * @return \App\Form\MediaSocialNetworkType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MediaSocialNetworkType'] = new \App\Form\MediaSocialNetworkType();
    }
}
