<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MediaType' shared autowired service.
     *
     * @return \App\Form\MediaType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MediaType'] = new \App\Form\MediaType(($container->privates['App\\Repository\\MediaInterestRepository'] ?? $container->load('getMediaInterestRepositoryService')), ($container->privates['App\\Repository\\MediaLanguagesRepository'] ?? $container->load('getMediaLanguagesRepositoryService')), ($container->privates['App\\Repository\\MediaGeographicalSystemRepository'] ?? $container->load('getMediaGeographicalSystemRepositoryService')), ($container->privates['App\\Repository\\MediaSocialNetworkRepository'] ?? $container->load('getMediaSocialNetworkRepositoryService')));
    }
}
