<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\MailCommand' shared autowired service.
     *
     * @return \App\Command\MailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\MailCommand'] = $instance = new \App\Command\MailCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('mail:send');

        return $instance;
    }
}
