<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSettingRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SettingRepository' shared autowired service.
     *
     * @return \App\Repository\SettingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SettingRepository'] = new \App\Repository\SettingRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
