<?php

namespace Container1afqmMM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Table' shared autowired service.
     *
     * @return \App\Service\Table
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Table'] = new \App\Service\Table(($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
