<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBomoIcal_IcsProviderService extends App_KernelProdContainer
{
    /*
     * Gets the public 'bomo_ical.ics_provider' shared service.
     *
     * @return \BOMO\IcalBundle\Provider\IcsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['bomo_ical.ics_provider'] = new \BOMO\IcalBundle\Provider\IcsProvider();
    }
}
