<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCron_ExecutorService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cron.executor' shared service.
     *
     * @return \Cron\Executor\Executor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['cron.executor'] = new \Cron\Executor\Executor();
    }
}
