<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronStartCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.Cron\CronBundle\Command\CronStartCommand' shared service.
     *
     * @return \Cron\CronBundle\Command\CronStartCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.Cron\\CronBundle\\Command\\CronStartCommand'] = new \Cron\CronBundle\Command\CronStartCommand($container);
    }
}
