<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCron_ResolverService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cron.resolver' shared service.
     *
     * @return \Cron\CronBundle\Cron\Resolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['cron.resolver'] = new \Cron\CronBundle\Cron\Resolver(($container->services['cron.manager'] ?? $container->load('getCron_ManagerService')), new \Cron\CronBundle\Cron\CommandBuilder('prod'), \dirname(__DIR__, 4));
    }
}
