<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeographicalSystemRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GeographicalSystemRepository' shared autowired service.
     *
     * @return \App\Repository\GeographicalSystemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GeographicalSystemRepository'] = new \App\Repository\GeographicalSystemRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), ($container->privates['App\\Repository\\SettingRepository'] ?? $container->load('getSettingRepositoryService')));
    }
}
