<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_Http_MessageFactoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'hwi_oauth.http.message_factory' shared service.
     *
     * @return \Http\Message\MessageFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['hwi_oauth.http.message_factory'] = \Http\Discovery\MessageFactoryDiscovery::find();
    }
}
