<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwnermap_SecuredAreaService extends App_KernelProdContainer
{
    /*
     * Gets the public 'hwi_oauth.resource_ownermap.secured_area' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMap
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['hwi_oauth.resource_ownermap.secured_area'] = $instance = new \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMap(($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), $container->parameters['hwi_oauth.resource_owners'], $container->parameters['hwi_oauth.resource_ownermap.configured.secured_area']);

        $instance->setContainer($container);

        return $instance;
    }
}
