<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkSearchTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Search\LinkSearchType' shared autowired service.
     *
     * @return \App\Form\Search\LinkSearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Search\\LinkSearchType'] = new \App\Form\Search\LinkSearchType(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
