<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkCaptureTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\LinkCaptureType' shared autowired service.
     *
     * @return \App\Form\LinkCaptureType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\LinkCaptureType'] = new \App\Form\LinkCaptureType();
    }
}
