<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterSubscriptionActionService extends App_KernelProdContainer
{
    /*
     * Gets the public 'BenTools\WebPushBundle\Action\RegisterSubscriptionAction' shared service.
     *
     * @return \BenTools\WebPushBundle\Action\RegisterSubscriptionAction
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['BenTools\\WebPushBundle\\Action\\RegisterSubscriptionAction'] = new \BenTools\WebPushBundle\Action\RegisterSubscriptionAction(($container->privates['BenTools\\WebPushBundle\\Model\\Subscription\\UserSubscriptionManagerRegistry'] ?? $container->load('getUserSubscriptionManagerRegistryService')));
    }
}
