<?php

namespace Container4xAh3uV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.gOCcGYL'] ?? $container->get_ServiceLocator_GOCcGYLService()), ($container->privates['.service_locator._L933XU'] ?? $container->load('get_ServiceLocator_L933XUService')), ['main' => [0 => ($container->privates['security.authenticator.guard.main.0'] ?? $container->load('getSecurity_Authenticator_Guard_Main_0Service'))], 'secured_area' => [0 => ($container->privates['security.authenticator.guard.secured_area.0'] ?? $container->load('getSecurity_Authenticator_Guard_SecuredArea_0Service')), 1 => ($container->privates['security.authenticator.oauth.secured_area'] ?? $container->load('getSecurity_Authenticator_Oauth_SecuredAreaService'))]], true);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
