<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1afqmMM\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1afqmMM/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container1afqmMM.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container1afqmMM\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container1afqmMM\App_KernelProdContainer([
    'container.build_hash' => '1afqmMM',
    'container.build_id' => '26763573',
    'container.build_time' => 1702403834,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1afqmMM');
