<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4xAh3uV\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4xAh3uV/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container4xAh3uV.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container4xAh3uV\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container4xAh3uV\App_KernelProdContainer([
    'container.build_hash' => '4xAh3uV',
    'container.build_id' => 'c21d2d7a',
    'container.build_time' => 1702305543,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4xAh3uV');
