<?php

namespace ContainerRIOpP3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkCaptureRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\LinkCaptureRepository' shared autowired service.
     *
     * @return \App\Repository\LinkCaptureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'LinkCaptureRepository.php';

        return $container->privates['App\\Repository\\LinkCaptureRepository'] = new \App\Repository\LinkCaptureRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
