<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXUbZkoD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXUbZkoD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXUbZkoD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXUbZkoD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXUbZkoD\App_KernelDevDebugContainer([
    'container.build_hash' => 'XUbZkoD',
    'container.build_id' => 'f5019020',
    'container.build_time' => 1702346005,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXUbZkoD');
