<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MailHistory extends \App\Entity\MailHistory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'template', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'sender', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'reply_to', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'receiver', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'cc', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'subject', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'variables', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'attachments', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'status', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'resend_count', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'sent_at', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'created_by'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'template', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'sender', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'reply_to', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'receiver', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'cc', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'subject', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'variables', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'attachments', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'status', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'resend_count', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'sent_at', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'created_at', '' . "\0" . 'App\\Entity\\MailHistory' . "\0" . 'created_by'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MailHistory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTemplate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemplate', []);

        return parent::getTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemplate(?string $template): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemplate', [$template]);

        return parent::setTemplate($template);
    }

    /**
     * {@inheritDoc}
     */
    public function getSender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSender', []);

        return parent::getSender();
    }

    /**
     * {@inheritDoc}
     */
    public function setSender(?string $sender): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSender', [$sender]);

        return parent::setSender($sender);
    }

    /**
     * {@inheritDoc}
     */
    public function getReplyTo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReplyTo', []);

        return parent::getReplyTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setReplyTo(?string $reply_to): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReplyTo', [$reply_to]);

        return parent::setReplyTo($reply_to);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiver(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiver', []);

        return parent::getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiver(?string $receiver): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiver', [$receiver]);

        return parent::setReceiver($receiver);
    }

    /**
     * {@inheritDoc}
     */
    public function getCc(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCc', []);

        return parent::getCc();
    }

    /**
     * {@inheritDoc}
     */
    public function setCc(array $cc = array (
)): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCc', [$cc]);

        return parent::setCc($cc);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject(?string $subject): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?string $status): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getVariables(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVariables', []);

        return parent::getVariables();
    }

    /**
     * {@inheritDoc}
     */
    public function setVariables(?array $variables): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVariables', [$variables]);

        return parent::setVariables($variables);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', []);

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachments(?array $attachments): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachments', [$attachments]);

        return parent::setAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function getResendCount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResendCount', []);

        return parent::getResendCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setResendCount(?int $resend_count): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResendCount', [$resend_count]);

        return parent::setResendCount($resend_count);
    }

    /**
     * {@inheritDoc}
     */
    public function getSentAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentAt', []);

        return parent::getSentAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSentAt(?\DateTimeInterface $sent_at): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSentAt', [$sent_at]);

        return parent::setSentAt($sent_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(?\DateTimeInterface $created_at): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(?int $created_by): \App\Entity\MailHistory
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$created_by]);

        return parent::setCreatedBy($created_by);
    }

}
